### ISSUE TITLE
Calendar for booking cars

### ISSUE THREAD

**Issue by dorthrithil** [Carbulator/carbulator-client#91]
Too reserve the car for some days a calendar would be useful.

TODOs:

- [x] Create server event model
- [x] POST event route
- [x] PUT event route
- [x] GET event route
- [x] GET events route (from / to)
- [x] DELETE event route
- [x] Create client event model
- [x] Create event service
- [x] Create calendar module
- [x] Create event modal
- [x] Mark today bold
- [x] Handle drag & drop
- [x] Add username to title in calendar view

**Comment by dorthrithil** [comment]
For calendar: https://www.primefaces.org/primeng/#/fullcalendar
TODO: Test package size - I only need the calendar. Is the library tree shakeable?
